### ISSUE TITLE
Does this build on OS X 10.6.8 with Xcode 3.2.6?

### ISSUE THREAD

**Issue by MiqViq** [wollardj/Munki-Manifest-Selector#1]

**Comment by ghost** [comment]
I'm not sure if it will compile or not. I suppose that's a factor of the installed SDKs. However, it should _not_ run on anything lower than 10.7 because of its use of NSPopover.

**Comment by MiqViq** [comment]
Yes, I noticed the same as it gave errors pointing towards NSPopover and such.

So it needs at least OS X 10.7 to build and use.
