### ISSUE TITLE
Formatting of Manifests.plist?

### ISSUE THREAD

**Issue by MiqViq** [wollardj/Munki-Manifest-Selector#2]
How should the Manifests.plist be formatted?
Can you include a brief example documentation?

**Comment by ghost** [comment]
I just posted this last night: http://denisonmac.wordpress.com/2013/02/09/munki-manifest-selector/

I kind of did it in a hurry, so let me know if you find any problems with it.

**Comment by MiqViq** [comment]
Thanks for the info, I found out the answer by investigating the source code a little more.

**Comment by jonbrown21** [comment]
The code on your blog post is missing / stripped out, can you create a properly formatted .plist file that could be used in the actual repo?
